"""Regression — production controller reproduces the ORACLE-generated golden.

Loads ``tests/ref/golden/controller_gold_trajectory.jsonl`` (regenerated by
regenerate_golden_from_oracle.py) and asserts the production controller +
fake-archer replay reproduce it exactly: controller fields, then per-rank
slot_after / direct / staging.

This is the stored-golden anchor (fast regression + the artifact the C++
real-archer test replays).  If the controller changes behaviour, this fails and
you regenerate ONLY after confirming the new behaviour is intended.

Run:  pytest tests/ref/test_golden_regression.py -q
"""
from __future__ import annotations

import json
import os
import sys
from collections import OrderedDict

import pytest

sys.path.insert(0, os.path.dirname(__file__))

from reference import RefArcher, demand_matrix          # noqa: E402
import prod_driver as pd                                  # noqa: E402

L = 0
GOLD = os.path.join(os.path.dirname(__file__), "golden",
                    "controller_gold_trajectory.jsonl")


def _load():
    with open(GOLD) as f:
        lines = [json.loads(ln) for ln in f if ln.strip()]
    grouped = OrderedDict()
    for ln in lines:
        grouped.setdefault(ln["trajectory"], []).append(ln)
    return grouped


GROUPS = _load()


def _ek(k):
    return None if k is None else [int(k[0]), int(k[1])]


@pytest.mark.parametrize("traj", list(GROUPS.keys()))
def test_golden_trajectory(traj):
    lines = GROUPS[traj]
    cfg = lines[0]["config"]
    ep, cap, ne = cfg["ep_size"], cfg["cap_per_rank"], cfg["num_experts"]
    prod = pd.make_prod(ep, cap, ne, cfg["owner_policy"], cfg["evict_policy"])
    physical = [RefArcher(cap) for _ in range(ep)]

    for ln in lines:
        ts = ln["trace_step"]
        exp = ln["expected"]
        step = {int(r): {int(e): c for e, c in d.items()}
                for r, d in ln["per_rank_demand"].items()}
        matrix = demand_matrix(ep, ne, step)

        hits, misses, shadow = pd.prod_plan_tuples(prod, matrix, L)

        # ---- controller fields vs golden ----
        got_hits = sorted([_ek((l, e)), r, s]
                          for (l, e, s), r in
                          [((l, e, s), r) for r in range(ep)
                           for (l, e, s) in hits[r]])
        exp_hits = sorted([o["expert"], o["owner_rank"], o["slot"]]
                          for o in exp["hit_ops"])
        assert got_hits == exp_hits, f"[{traj} ts={ts}] hit_ops"

        got_shadow = {str(r): [_ek(s) for s in shadow[r]] for r in range(ep)}
        assert got_shadow == exp["shadow_after"], f"[{traj} ts={ts}] shadow_after"

        got_fetch = sorted(
            [_ek((l, e)), r, dst, _ek((vl, ve) if vl >= 0 else None), order]
            for r in range(ep)
            for (l, e, dst, vl, ve, order) in misses[r])
        exp_fetch = sorted([o["expert"], o["fetcher_rank"], o["dst_slot"],
                            o["victim"], o["order"]] for o in exp["fetch_ops"])
        assert got_fetch == exp_fetch, f"[{traj} ts={ts}] fetch_ops"

        # ---- archer replay vs golden (slot_after / direct / staging) ----
        for r in range(ep):
            gr = ln["archer_replay"][str(r)]
            physical[r].submit_plan(hits[r], misses[r])
            assert [_ek(s) for s in physical[r].get_cached_slots()] == \
                gr["slot_after"], f"[{traj} ts={ts} r={r}] slot_after"
            assert physical[r].direct == gr["direct"], \
                f"[{traj} ts={ts} r={r}] direct {physical[r].direct}!={gr['direct']}"
            assert physical[r].staging == gr["staging"], \
                f"[{traj} ts={ts} r={r}] staging {physical[r].staging}!={gr['staging']}"
            physical[r].direct = physical[r].staging = 0

        pd.prod_bump(prod)


if __name__ == "__main__":
    for t in GROUPS:
        test_golden_trajectory(t)
    print("golden regression: ALL PASS")
